// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType - Type of event
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED           EventType = 0
	EventType_EVENT_TYPE_STEP_STARTED          EventType = 1
	EventType_EVENT_TYPE_STEP_FINISHED         EventType = 2
	EventType_EVENT_TYPE_NODE_STATUS_CHANGED   EventType = 3
	EventType_EVENT_TYPE_LLM_CALL_STARTED      EventType = 4
	EventType_EVENT_TYPE_LLM_CALL_COMPLETED    EventType = 5
	EventType_EVENT_TYPE_TOOL_INVOKED          EventType = 6
	EventType_EVENT_TYPE_TOOL_RETURNED         EventType = 7
	EventType_EVENT_TYPE_NODE_CREATED          EventType = 8
	EventType_EVENT_TYPE_PLAN_RECEIVED         EventType = 9
	EventType_EVENT_TYPE_NODE_ADDED            EventType = 10
	EventType_EVENT_TYPE_EDGE_ADDED            EventType = 11
	EventType_EVENT_TYPE_INNER_GRAPH_BUILT     EventType = 12
	EventType_EVENT_TYPE_NODE_RESULT_AVAILABLE EventType = 13
	EventType_EVENT_TYPE_RUN_STARTED           EventType = 14
	EventType_EVENT_TYPE_RUN_FINISHED          EventType = 15
	EventType_EVENT_TYPE_RUN_ERROR             EventType = 16
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_STEP_STARTED",
		2:  "EVENT_TYPE_STEP_FINISHED",
		3:  "EVENT_TYPE_NODE_STATUS_CHANGED",
		4:  "EVENT_TYPE_LLM_CALL_STARTED",
		5:  "EVENT_TYPE_LLM_CALL_COMPLETED",
		6:  "EVENT_TYPE_TOOL_INVOKED",
		7:  "EVENT_TYPE_TOOL_RETURNED",
		8:  "EVENT_TYPE_NODE_CREATED",
		9:  "EVENT_TYPE_PLAN_RECEIVED",
		10: "EVENT_TYPE_NODE_ADDED",
		11: "EVENT_TYPE_EDGE_ADDED",
		12: "EVENT_TYPE_INNER_GRAPH_BUILT",
		13: "EVENT_TYPE_NODE_RESULT_AVAILABLE",
		14: "EVENT_TYPE_RUN_STARTED",
		15: "EVENT_TYPE_RUN_FINISHED",
		16: "EVENT_TYPE_RUN_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":           0,
		"EVENT_TYPE_STEP_STARTED":          1,
		"EVENT_TYPE_STEP_FINISHED":         2,
		"EVENT_TYPE_NODE_STATUS_CHANGED":   3,
		"EVENT_TYPE_LLM_CALL_STARTED":      4,
		"EVENT_TYPE_LLM_CALL_COMPLETED":    5,
		"EVENT_TYPE_TOOL_INVOKED":          6,
		"EVENT_TYPE_TOOL_RETURNED":         7,
		"EVENT_TYPE_NODE_CREATED":          8,
		"EVENT_TYPE_PLAN_RECEIVED":         9,
		"EVENT_TYPE_NODE_ADDED":            10,
		"EVENT_TYPE_EDGE_ADDED":            11,
		"EVENT_TYPE_INNER_GRAPH_BUILT":     12,
		"EVENT_TYPE_NODE_RESULT_AVAILABLE": 13,
		"EVENT_TYPE_RUN_STARTED":           14,
		"EVENT_TYPE_RUN_FINISHED":          15,
		"EVENT_TYPE_RUN_ERROR":             16,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

// ConnectionStatus - WebSocket connection status
type ConnectionStatus int32

const (
	ConnectionStatus_CONNECTION_STATUS_UNSPECIFIED  ConnectionStatus = 0
	ConnectionStatus_CONNECTION_STATUS_CONNECTING   ConnectionStatus = 1
	ConnectionStatus_CONNECTION_STATUS_CONNECTED    ConnectionStatus = 2
	ConnectionStatus_CONNECTION_STATUS_DISCONNECTED ConnectionStatus = 3
)

// Enum value maps for ConnectionStatus.
var (
	ConnectionStatus_name = map[int32]string{
		0: "CONNECTION_STATUS_UNSPECIFIED",
		1: "CONNECTION_STATUS_CONNECTING",
		2: "CONNECTION_STATUS_CONNECTED",
		3: "CONNECTION_STATUS_DISCONNECTED",
	}
	ConnectionStatus_value = map[string]int32{
		"CONNECTION_STATUS_UNSPECIFIED":  0,
		"CONNECTION_STATUS_CONNECTING":   1,
		"CONNECTION_STATUS_CONNECTED":    2,
		"CONNECTION_STATUS_DISCONNECTED": 3,
	}
)

func (x ConnectionStatus) Enum() *ConnectionStatus {
	p := new(ConnectionStatus)
	*p = x
	return p
}

func (x ConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_events_proto_enumTypes[1].Descriptor()
}

func (ConnectionStatus) Type() protoreflect.EnumType {
	return &file_proto_events_proto_enumTypes[1]
}

func (x ConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionStatus.Descriptor instead.
func (ConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

// LlmMessage - Message in a prompt
type LlmMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmMessage) Reset() {
	*x = LlmMessage{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmMessage) ProtoMessage() {}

func (x *LlmMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmMessage.ProtoReflect.Descriptor instead.
func (*LlmMessage) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *LlmMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LlmMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// StepStartedPayload - When a step starts
type StepStartedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeGoal      string                 `protobuf:"bytes,3,opt,name=node_goal,json=nodeGoal,proto3" json:"node_goal,omitempty"`
	RootId        string                 `protobuf:"bytes,4,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStartedPayload) Reset() {
	*x = StepStartedPayload{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStartedPayload) ProtoMessage() {}

func (x *StepStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStartedPayload.ProtoReflect.Descriptor instead.
func (*StepStartedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *StepStartedPayload) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *StepStartedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StepStartedPayload) GetNodeGoal() string {
	if x != nil {
		return x.NodeGoal
	}
	return ""
}

func (x *StepStartedPayload) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

// StepFinishedPayload - When a step finishes
type StepFinishedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Step            int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActionName      string                 `protobuf:"bytes,3,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	StatusAfter     string                 `protobuf:"bytes,4,opt,name=status_after,json=statusAfter,proto3" json:"status_after,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StepFinishedPayload) Reset() {
	*x = StepFinishedPayload{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepFinishedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFinishedPayload) ProtoMessage() {}

func (x *StepFinishedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFinishedPayload.ProtoReflect.Descriptor instead.
func (*StepFinishedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *StepFinishedPayload) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *StepFinishedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StepFinishedPayload) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *StepFinishedPayload) GetStatusAfter() string {
	if x != nil {
		return x.StatusAfter
	}
	return ""
}

func (x *StepFinishedPayload) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// NodeStatusChangePayload - Node status changes
type NodeStatusChangePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeGoal      string                 `protobuf:"bytes,2,opt,name=node_goal,json=nodeGoal,proto3" json:"node_goal,omitempty"`
	OldStatus     string                 `protobuf:"bytes,3,opt,name=old_status,json=oldStatus,proto3" json:"old_status,omitempty"`
	NewStatus     string                 `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Step          *int32                 `protobuf:"varint,5,opt,name=step,proto3,oneof" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusChangePayload) Reset() {
	*x = NodeStatusChangePayload{}
	mi := &file_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusChangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusChangePayload) ProtoMessage() {}

func (x *NodeStatusChangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusChangePayload.ProtoReflect.Descriptor instead.
func (*NodeStatusChangePayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatusChangePayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatusChangePayload) GetNodeGoal() string {
	if x != nil {
		return x.NodeGoal
	}
	return ""
}

func (x *NodeStatusChangePayload) GetOldStatus() string {
	if x != nil {
		return x.OldStatus
	}
	return ""
}

func (x *NodeStatusChangePayload) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *NodeStatusChangePayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

// TokenUsage - Token usage info
type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	Error            *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	NodeId           *string                `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *TokenUsage) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

// LlmCallStartedPayload - LLM call starts
type LlmCallStartedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentClass    string                 `protobuf:"bytes,1,opt,name=agent_class,json=agentClass,proto3" json:"agent_class,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        []*LlmMessage          `protobuf:"bytes,3,rep,name=prompt,proto3" json:"prompt,omitempty"`
	PromptPreview string                 `protobuf:"bytes,4,opt,name=prompt_preview,json=promptPreview,proto3" json:"prompt_preview,omitempty"`
	Step          *int32                 `protobuf:"varint,5,opt,name=step,proto3,oneof" json:"step,omitempty"`
	NodeId        *string                `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	ActionName    *string                `protobuf:"bytes,7,opt,name=action_name,json=actionName,proto3,oneof" json:"action_name,omitempty"`
	CallId        string                 `protobuf:"bytes,8,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LlmCallStartedPayload) Reset() {
	*x = LlmCallStartedPayload{}
	mi := &file_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmCallStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmCallStartedPayload) ProtoMessage() {}

func (x *LlmCallStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmCallStartedPayload.ProtoReflect.Descriptor instead.
func (*LlmCallStartedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *LlmCallStartedPayload) GetAgentClass() string {
	if x != nil {
		return x.AgentClass
	}
	return ""
}

func (x *LlmCallStartedPayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LlmCallStartedPayload) GetPrompt() []*LlmMessage {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *LlmCallStartedPayload) GetPromptPreview() string {
	if x != nil {
		return x.PromptPreview
	}
	return ""
}

func (x *LlmCallStartedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *LlmCallStartedPayload) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *LlmCallStartedPayload) GetActionName() string {
	if x != nil && x.ActionName != nil {
		return *x.ActionName
	}
	return ""
}

func (x *LlmCallStartedPayload) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// LlmCallCompletedPayload - LLM call completes
type LlmCallCompletedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentClass      string                 `protobuf:"bytes,1,opt,name=agent_class,json=agentClass,proto3" json:"agent_class,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Response        string                 `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	ResultSummary   string                 `protobuf:"bytes,5,opt,name=result_summary,json=resultSummary,proto3" json:"result_summary,omitempty"`
	Error           *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Step            *int32                 `protobuf:"varint,7,opt,name=step,proto3,oneof" json:"step,omitempty"`
	NodeId          *string                `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	TokenUsage      *TokenUsage            `protobuf:"bytes,9,opt,name=token_usage,json=tokenUsage,proto3,oneof" json:"token_usage,omitempty"`
	ActionName      *string                `protobuf:"bytes,10,opt,name=action_name,json=actionName,proto3,oneof" json:"action_name,omitempty"`
	CallId          string                 `protobuf:"bytes,11,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LlmCallCompletedPayload) Reset() {
	*x = LlmCallCompletedPayload{}
	mi := &file_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LlmCallCompletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LlmCallCompletedPayload) ProtoMessage() {}

func (x *LlmCallCompletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LlmCallCompletedPayload.ProtoReflect.Descriptor instead.
func (*LlmCallCompletedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *LlmCallCompletedPayload) GetAgentClass() string {
	if x != nil {
		return x.AgentClass
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *LlmCallCompletedPayload) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetResultSummary() string {
	if x != nil {
		return x.ResultSummary
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *LlmCallCompletedPayload) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *LlmCallCompletedPayload) GetActionName() string {
	if x != nil && x.ActionName != nil {
		return *x.ActionName
	}
	return ""
}

func (x *LlmCallCompletedPayload) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// ToolInvokedPayload - Tool is invoked
type ToolInvokedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ApiName       string                 `protobuf:"bytes,2,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	ArgsSummary   string                 `protobuf:"bytes,3,opt,name=args_summary,json=argsSummary,proto3" json:"args_summary,omitempty"`
	NodeId        *string                `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	Step          *int32                 `protobuf:"varint,5,opt,name=step,proto3,oneof" json:"step,omitempty"`
	AgentClass    *string                `protobuf:"bytes,6,opt,name=agent_class,json=agentClass,proto3,oneof" json:"agent_class,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,7,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInvokedPayload) Reset() {
	*x = ToolInvokedPayload{}
	mi := &file_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInvokedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInvokedPayload) ProtoMessage() {}

func (x *ToolInvokedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInvokedPayload.ProtoReflect.Descriptor instead.
func (*ToolInvokedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *ToolInvokedPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolInvokedPayload) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *ToolInvokedPayload) GetArgsSummary() string {
	if x != nil {
		return x.ArgsSummary
	}
	return ""
}

func (x *ToolInvokedPayload) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *ToolInvokedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *ToolInvokedPayload) GetAgentClass() string {
	if x != nil && x.AgentClass != nil {
		return *x.AgentClass
	}
	return ""
}

func (x *ToolInvokedPayload) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

// ToolReturnedPayload - Tool returns
type ToolReturnedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ToolName        string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ApiName         string                 `protobuf:"bytes,2,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ResultSummary   string                 `protobuf:"bytes,5,opt,name=result_summary,json=resultSummary,proto3" json:"result_summary,omitempty"`
	Error           *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	NodeId          *string                `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	Step            *int32                 `protobuf:"varint,8,opt,name=step,proto3,oneof" json:"step,omitempty"`
	AgentClass      *string                `protobuf:"bytes,9,opt,name=agent_class,json=agentClass,proto3,oneof" json:"agent_class,omitempty"`
	ToolCallId      string                 `protobuf:"bytes,10,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolReturnedPayload) Reset() {
	*x = ToolReturnedPayload{}
	mi := &file_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolReturnedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolReturnedPayload) ProtoMessage() {}

func (x *ToolReturnedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolReturnedPayload.ProtoReflect.Descriptor instead.
func (*ToolReturnedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *ToolReturnedPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolReturnedPayload) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *ToolReturnedPayload) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ToolReturnedPayload) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ToolReturnedPayload) GetResultSummary() string {
	if x != nil {
		return x.ResultSummary
	}
	return ""
}

func (x *ToolReturnedPayload) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ToolReturnedPayload) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *ToolReturnedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *ToolReturnedPayload) GetAgentClass() string {
	if x != nil && x.AgentClass != nil {
		return *x.AgentClass
	}
	return ""
}

func (x *ToolReturnedPayload) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

// NodeCreatedPayload - Node is created
type NodeCreatedPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeNid           string                 `protobuf:"bytes,2,opt,name=node_nid,json=nodeNid,proto3" json:"node_nid,omitempty"`
	NodeType          string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	TaskType          string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskGoal          string                 `protobuf:"bytes,5,opt,name=task_goal,json=taskGoal,proto3" json:"task_goal,omitempty"`
	Layer             int32                  `protobuf:"varint,6,opt,name=layer,proto3" json:"layer,omitempty"`
	OuterNodeId       *string                `protobuf:"bytes,7,opt,name=outer_node_id,json=outerNodeId,proto3,oneof" json:"outer_node_id,omitempty"`
	RootNodeId        string                 `protobuf:"bytes,8,opt,name=root_node_id,json=rootNodeId,proto3" json:"root_node_id,omitempty"`
	InitialParentNids []string               `protobuf:"bytes,9,rep,name=initial_parent_nids,json=initialParentNids,proto3" json:"initial_parent_nids,omitempty"`
	Step              *int32                 `protobuf:"varint,10,opt,name=step,proto3,oneof" json:"step,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeCreatedPayload) Reset() {
	*x = NodeCreatedPayload{}
	mi := &file_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCreatedPayload) ProtoMessage() {}

func (x *NodeCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCreatedPayload.ProtoReflect.Descriptor instead.
func (*NodeCreatedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *NodeCreatedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeCreatedPayload) GetNodeNid() string {
	if x != nil {
		return x.NodeNid
	}
	return ""
}

func (x *NodeCreatedPayload) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeCreatedPayload) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *NodeCreatedPayload) GetTaskGoal() string {
	if x != nil {
		return x.TaskGoal
	}
	return ""
}

func (x *NodeCreatedPayload) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *NodeCreatedPayload) GetOuterNodeId() string {
	if x != nil && x.OuterNodeId != nil {
		return *x.OuterNodeId
	}
	return ""
}

func (x *NodeCreatedPayload) GetRootNodeId() string {
	if x != nil {
		return x.RootNodeId
	}
	return ""
}

func (x *NodeCreatedPayload) GetInitialParentNids() []string {
	if x != nil {
		return x.InitialParentNids
	}
	return nil
}

func (x *NodeCreatedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

// PlanReceivedPayload - Plan is received
type PlanReceivedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RawPlan       *structpb.Struct       `protobuf:"bytes,2,opt,name=raw_plan,json=rawPlan,proto3" json:"raw_plan,omitempty"` // Using Struct for arbitrary JSON
	Step          *int32                 `protobuf:"varint,3,opt,name=step,proto3,oneof" json:"step,omitempty"`
	TaskType      *string                `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3,oneof" json:"task_type,omitempty"`
	TaskGoal      *string                `protobuf:"bytes,5,opt,name=task_goal,json=taskGoal,proto3,oneof" json:"task_goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanReceivedPayload) Reset() {
	*x = PlanReceivedPayload{}
	mi := &file_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanReceivedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanReceivedPayload) ProtoMessage() {}

func (x *PlanReceivedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanReceivedPayload.ProtoReflect.Descriptor instead.
func (*PlanReceivedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *PlanReceivedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PlanReceivedPayload) GetRawPlan() *structpb.Struct {
	if x != nil {
		return x.RawPlan
	}
	return nil
}

func (x *PlanReceivedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *PlanReceivedPayload) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

func (x *PlanReceivedPayload) GetTaskGoal() string {
	if x != nil && x.TaskGoal != nil {
		return *x.TaskGoal
	}
	return ""
}

// NodeAddedPayload - Node added to graph
type NodeAddedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GraphOwnerNodeId string                 `protobuf:"bytes,1,opt,name=graph_owner_node_id,json=graphOwnerNodeId,proto3" json:"graph_owner_node_id,omitempty"`
	AddedNodeId      string                 `protobuf:"bytes,2,opt,name=added_node_id,json=addedNodeId,proto3" json:"added_node_id,omitempty"`
	AddedNodeNid     string                 `protobuf:"bytes,3,opt,name=added_node_nid,json=addedNodeNid,proto3" json:"added_node_nid,omitempty"`
	Step             *int32                 `protobuf:"varint,4,opt,name=step,proto3,oneof" json:"step,omitempty"`
	TaskType         *string                `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3,oneof" json:"task_type,omitempty"`
	TaskGoal         *string                `protobuf:"bytes,6,opt,name=task_goal,json=taskGoal,proto3,oneof" json:"task_goal,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeAddedPayload) Reset() {
	*x = NodeAddedPayload{}
	mi := &file_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddedPayload) ProtoMessage() {}

func (x *NodeAddedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddedPayload.ProtoReflect.Descriptor instead.
func (*NodeAddedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *NodeAddedPayload) GetGraphOwnerNodeId() string {
	if x != nil {
		return x.GraphOwnerNodeId
	}
	return ""
}

func (x *NodeAddedPayload) GetAddedNodeId() string {
	if x != nil {
		return x.AddedNodeId
	}
	return ""
}

func (x *NodeAddedPayload) GetAddedNodeNid() string {
	if x != nil {
		return x.AddedNodeNid
	}
	return ""
}

func (x *NodeAddedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *NodeAddedPayload) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

func (x *NodeAddedPayload) GetTaskGoal() string {
	if x != nil && x.TaskGoal != nil {
		return *x.TaskGoal
	}
	return ""
}

// EdgeAddedPayload - Edge added to graph
type EdgeAddedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GraphOwnerNodeId string                 `protobuf:"bytes,1,opt,name=graph_owner_node_id,json=graphOwnerNodeId,proto3" json:"graph_owner_node_id,omitempty"`
	ParentNodeId     string                 `protobuf:"bytes,2,opt,name=parent_node_id,json=parentNodeId,proto3" json:"parent_node_id,omitempty"`
	ChildNodeId      string                 `protobuf:"bytes,3,opt,name=child_node_id,json=childNodeId,proto3" json:"child_node_id,omitempty"`
	ParentNodeNid    string                 `protobuf:"bytes,4,opt,name=parent_node_nid,json=parentNodeNid,proto3" json:"parent_node_nid,omitempty"`
	ChildNodeNid     string                 `protobuf:"bytes,5,opt,name=child_node_nid,json=childNodeNid,proto3" json:"child_node_nid,omitempty"`
	Step             *int32                 `protobuf:"varint,6,opt,name=step,proto3,oneof" json:"step,omitempty"`
	TaskType         *string                `protobuf:"bytes,7,opt,name=task_type,json=taskType,proto3,oneof" json:"task_type,omitempty"`
	TaskGoal         *string                `protobuf:"bytes,8,opt,name=task_goal,json=taskGoal,proto3,oneof" json:"task_goal,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EdgeAddedPayload) Reset() {
	*x = EdgeAddedPayload{}
	mi := &file_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeAddedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeAddedPayload) ProtoMessage() {}

func (x *EdgeAddedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeAddedPayload.ProtoReflect.Descriptor instead.
func (*EdgeAddedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *EdgeAddedPayload) GetGraphOwnerNodeId() string {
	if x != nil {
		return x.GraphOwnerNodeId
	}
	return ""
}

func (x *EdgeAddedPayload) GetParentNodeId() string {
	if x != nil {
		return x.ParentNodeId
	}
	return ""
}

func (x *EdgeAddedPayload) GetChildNodeId() string {
	if x != nil {
		return x.ChildNodeId
	}
	return ""
}

func (x *EdgeAddedPayload) GetParentNodeNid() string {
	if x != nil {
		return x.ParentNodeNid
	}
	return ""
}

func (x *EdgeAddedPayload) GetChildNodeNid() string {
	if x != nil {
		return x.ChildNodeNid
	}
	return ""
}

func (x *EdgeAddedPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *EdgeAddedPayload) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

func (x *EdgeAddedPayload) GetTaskGoal() string {
	if x != nil && x.TaskGoal != nil {
		return *x.TaskGoal
	}
	return ""
}

// InnerGraphBuiltPayload - Inner graph is built
type InnerGraphBuiltPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeCount     int32                  `protobuf:"varint,2,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount     int32                  `protobuf:"varint,3,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	NodeIds       []string               `protobuf:"bytes,4,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	Step          *int32                 `protobuf:"varint,5,opt,name=step,proto3,oneof" json:"step,omitempty"`
	TaskType      *string                `protobuf:"bytes,6,opt,name=task_type,json=taskType,proto3,oneof" json:"task_type,omitempty"`
	TaskGoal      *string                `protobuf:"bytes,7,opt,name=task_goal,json=taskGoal,proto3,oneof" json:"task_goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerGraphBuiltPayload) Reset() {
	*x = InnerGraphBuiltPayload{}
	mi := &file_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerGraphBuiltPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerGraphBuiltPayload) ProtoMessage() {}

func (x *InnerGraphBuiltPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerGraphBuiltPayload.ProtoReflect.Descriptor instead.
func (*InnerGraphBuiltPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *InnerGraphBuiltPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InnerGraphBuiltPayload) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *InnerGraphBuiltPayload) GetEdgeCount() int32 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *InnerGraphBuiltPayload) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *InnerGraphBuiltPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *InnerGraphBuiltPayload) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

func (x *InnerGraphBuiltPayload) GetTaskGoal() string {
	if x != nil && x.TaskGoal != nil {
		return *x.TaskGoal
	}
	return ""
}

// NodeResultAvailablePayload - Node result becomes available
type NodeResultAvailablePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	ResultSummary string                 `protobuf:"bytes,3,opt,name=result_summary,json=resultSummary,proto3" json:"result_summary,omitempty"`
	Step          *int32                 `protobuf:"varint,4,opt,name=step,proto3,oneof" json:"step,omitempty"`
	TaskType      *string                `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3,oneof" json:"task_type,omitempty"`
	TaskGoal      *string                `protobuf:"bytes,6,opt,name=task_goal,json=taskGoal,proto3,oneof" json:"task_goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResultAvailablePayload) Reset() {
	*x = NodeResultAvailablePayload{}
	mi := &file_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResultAvailablePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResultAvailablePayload) ProtoMessage() {}

func (x *NodeResultAvailablePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResultAvailablePayload.ProtoReflect.Descriptor instead.
func (*NodeResultAvailablePayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *NodeResultAvailablePayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeResultAvailablePayload) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *NodeResultAvailablePayload) GetResultSummary() string {
	if x != nil {
		return x.ResultSummary
	}
	return ""
}

func (x *NodeResultAvailablePayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *NodeResultAvailablePayload) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

func (x *NodeResultAvailablePayload) GetTaskGoal() string {
	if x != nil && x.TaskGoal != nil {
		return *x.TaskGoal
	}
	return ""
}

// RunStartedPayload - Run starts
type RunStartedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputData     *structpb.Struct       `protobuf:"bytes,1,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	RunMode       string                 `protobuf:"bytes,3,opt,name=run_mode,json=runMode,proto3" json:"run_mode,omitempty"`
	TimestampUtc  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp_utc,json=timestampUtc,proto3" json:"timestamp_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStartedPayload) Reset() {
	*x = RunStartedPayload{}
	mi := &file_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStartedPayload) ProtoMessage() {}

func (x *RunStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStartedPayload.ProtoReflect.Descriptor instead.
func (*RunStartedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *RunStartedPayload) GetInputData() *structpb.Struct {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *RunStartedPayload) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RunStartedPayload) GetRunMode() string {
	if x != nil {
		return x.RunMode
	}
	return ""
}

func (x *RunStartedPayload) GetTimestampUtc() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampUtc
	}
	return nil
}

// RunFinishedPayload - Run finishes
type RunFinishedPayload struct {
	state             protoimpl.MessageState                `protogen:"open.v1"`
	TotalSteps        int32                                 `protobuf:"varint,1,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	DurationSeconds   float64                               `protobuf:"fixed64,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	TotalNodes        int32                                 `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	TotalLlmCalls     int32                                 `protobuf:"varint,4,opt,name=total_llm_calls,json=totalLlmCalls,proto3" json:"total_llm_calls,omitempty"`
	TotalToolCalls    int32                                 `protobuf:"varint,5,opt,name=total_tool_calls,json=totalToolCalls,proto3" json:"total_tool_calls,omitempty"`
	TokenUsageSummary *RunFinishedPayload_TokenUsageSummary `protobuf:"bytes,6,opt,name=token_usage_summary,json=tokenUsageSummary,proto3" json:"token_usage_summary,omitempty"`
	NodeStatistics    *RunFinishedPayload_NodeStatistics    `protobuf:"bytes,7,opt,name=node_statistics,json=nodeStatistics,proto3" json:"node_statistics,omitempty"`
	SearchStatistics  *RunFinishedPayload_SearchStatistics  `protobuf:"bytes,8,opt,name=search_statistics,json=searchStatistics,proto3,oneof" json:"search_statistics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunFinishedPayload) Reset() {
	*x = RunFinishedPayload{}
	mi := &file_proto_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinishedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinishedPayload) ProtoMessage() {}

func (x *RunFinishedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinishedPayload.ProtoReflect.Descriptor instead.
func (*RunFinishedPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{16}
}

func (x *RunFinishedPayload) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *RunFinishedPayload) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *RunFinishedPayload) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *RunFinishedPayload) GetTotalLlmCalls() int32 {
	if x != nil {
		return x.TotalLlmCalls
	}
	return 0
}

func (x *RunFinishedPayload) GetTotalToolCalls() int32 {
	if x != nil {
		return x.TotalToolCalls
	}
	return 0
}

func (x *RunFinishedPayload) GetTokenUsageSummary() *RunFinishedPayload_TokenUsageSummary {
	if x != nil {
		return x.TokenUsageSummary
	}
	return nil
}

func (x *RunFinishedPayload) GetNodeStatistics() *RunFinishedPayload_NodeStatistics {
	if x != nil {
		return x.NodeStatistics
	}
	return nil
}

func (x *RunFinishedPayload) GetSearchStatistics() *RunFinishedPayload_SearchStatistics {
	if x != nil {
		return x.SearchStatistics
	}
	return nil
}

// RunErrorPayload - Run error
type RunErrorPayload struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	ErrorType     string                   `protobuf:"bytes,1,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"`
	ErrorMessage  string                   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StackTrace    string                   `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	NodeId        *string                  `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	Step          *int32                   `protobuf:"varint,5,opt,name=step,proto3,oneof" json:"step,omitempty"`
	Context       *RunErrorPayload_Context `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunErrorPayload) Reset() {
	*x = RunErrorPayload{}
	mi := &file_proto_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunErrorPayload) ProtoMessage() {}

func (x *RunErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunErrorPayload.ProtoReflect.Descriptor instead.
func (*RunErrorPayload) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{17}
}

func (x *RunErrorPayload) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *RunErrorPayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RunErrorPayload) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *RunErrorPayload) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *RunErrorPayload) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *RunErrorPayload) GetContext() *RunErrorPayload_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

// Event - The main event message that wraps all event types
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType EventType              `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=events.EventType" json:"event_type,omitempty"`
	RunId     *string                `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	// One of the following will be set based on event_type
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_StepStarted
	//	*Event_StepFinished
	//	*Event_NodeStatusChanged
	//	*Event_LlmCallStarted
	//	*Event_LlmCallCompleted
	//	*Event_ToolInvoked
	//	*Event_ToolReturned
	//	*Event_NodeCreated
	//	*Event_PlanReceived
	//	*Event_NodeAdded
	//	*Event_EdgeAdded
	//	*Event_InnerGraphBuilt
	//	*Event_NodeResultAvailable
	//	*Event_RunStarted
	//	*Event_RunFinished
	//	*Event_RunError
	//	*Event_UnknownPayload
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{18}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetStepStarted() *StepStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_StepStarted); ok {
			return x.StepStarted
		}
	}
	return nil
}

func (x *Event) GetStepFinished() *StepFinishedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_StepFinished); ok {
			return x.StepFinished
		}
	}
	return nil
}

func (x *Event) GetNodeStatusChanged() *NodeStatusChangePayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_NodeStatusChanged); ok {
			return x.NodeStatusChanged
		}
	}
	return nil
}

func (x *Event) GetLlmCallStarted() *LlmCallStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_LlmCallStarted); ok {
			return x.LlmCallStarted
		}
	}
	return nil
}

func (x *Event) GetLlmCallCompleted() *LlmCallCompletedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_LlmCallCompleted); ok {
			return x.LlmCallCompleted
		}
	}
	return nil
}

func (x *Event) GetToolInvoked() *ToolInvokedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolInvoked); ok {
			return x.ToolInvoked
		}
	}
	return nil
}

func (x *Event) GetToolReturned() *ToolReturnedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_ToolReturned); ok {
			return x.ToolReturned
		}
	}
	return nil
}

func (x *Event) GetNodeCreated() *NodeCreatedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_NodeCreated); ok {
			return x.NodeCreated
		}
	}
	return nil
}

func (x *Event) GetPlanReceived() *PlanReceivedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_PlanReceived); ok {
			return x.PlanReceived
		}
	}
	return nil
}

func (x *Event) GetNodeAdded() *NodeAddedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_NodeAdded); ok {
			return x.NodeAdded
		}
	}
	return nil
}

func (x *Event) GetEdgeAdded() *EdgeAddedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_EdgeAdded); ok {
			return x.EdgeAdded
		}
	}
	return nil
}

func (x *Event) GetInnerGraphBuilt() *InnerGraphBuiltPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_InnerGraphBuilt); ok {
			return x.InnerGraphBuilt
		}
	}
	return nil
}

func (x *Event) GetNodeResultAvailable() *NodeResultAvailablePayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_NodeResultAvailable); ok {
			return x.NodeResultAvailable
		}
	}
	return nil
}

func (x *Event) GetRunStarted() *RunStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunStarted); ok {
			return x.RunStarted
		}
	}
	return nil
}

func (x *Event) GetRunFinished() *RunFinishedPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunFinished); ok {
			return x.RunFinished
		}
	}
	return nil
}

func (x *Event) GetRunError() *RunErrorPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_RunError); ok {
			return x.RunError
		}
	}
	return nil
}

func (x *Event) GetUnknownPayload() *structpb.Struct {
	if x != nil {
		if x, ok := x.Payload.(*Event_UnknownPayload); ok {
			return x.UnknownPayload
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_StepStarted struct {
	StepStarted *StepStartedPayload `protobuf:"bytes,5,opt,name=step_started,json=stepStarted,proto3,oneof"`
}

type Event_StepFinished struct {
	StepFinished *StepFinishedPayload `protobuf:"bytes,6,opt,name=step_finished,json=stepFinished,proto3,oneof"`
}

type Event_NodeStatusChanged struct {
	NodeStatusChanged *NodeStatusChangePayload `protobuf:"bytes,7,opt,name=node_status_changed,json=nodeStatusChanged,proto3,oneof"`
}

type Event_LlmCallStarted struct {
	LlmCallStarted *LlmCallStartedPayload `protobuf:"bytes,8,opt,name=llm_call_started,json=llmCallStarted,proto3,oneof"`
}

type Event_LlmCallCompleted struct {
	LlmCallCompleted *LlmCallCompletedPayload `protobuf:"bytes,9,opt,name=llm_call_completed,json=llmCallCompleted,proto3,oneof"`
}

type Event_ToolInvoked struct {
	ToolInvoked *ToolInvokedPayload `protobuf:"bytes,10,opt,name=tool_invoked,json=toolInvoked,proto3,oneof"`
}

type Event_ToolReturned struct {
	ToolReturned *ToolReturnedPayload `protobuf:"bytes,11,opt,name=tool_returned,json=toolReturned,proto3,oneof"`
}

type Event_NodeCreated struct {
	NodeCreated *NodeCreatedPayload `protobuf:"bytes,12,opt,name=node_created,json=nodeCreated,proto3,oneof"`
}

type Event_PlanReceived struct {
	PlanReceived *PlanReceivedPayload `protobuf:"bytes,13,opt,name=plan_received,json=planReceived,proto3,oneof"`
}

type Event_NodeAdded struct {
	NodeAdded *NodeAddedPayload `protobuf:"bytes,14,opt,name=node_added,json=nodeAdded,proto3,oneof"`
}

type Event_EdgeAdded struct {
	EdgeAdded *EdgeAddedPayload `protobuf:"bytes,15,opt,name=edge_added,json=edgeAdded,proto3,oneof"`
}

type Event_InnerGraphBuilt struct {
	InnerGraphBuilt *InnerGraphBuiltPayload `protobuf:"bytes,16,opt,name=inner_graph_built,json=innerGraphBuilt,proto3,oneof"`
}

type Event_NodeResultAvailable struct {
	NodeResultAvailable *NodeResultAvailablePayload `protobuf:"bytes,17,opt,name=node_result_available,json=nodeResultAvailable,proto3,oneof"`
}

type Event_RunStarted struct {
	RunStarted *RunStartedPayload `protobuf:"bytes,18,opt,name=run_started,json=runStarted,proto3,oneof"`
}

type Event_RunFinished struct {
	RunFinished *RunFinishedPayload `protobuf:"bytes,19,opt,name=run_finished,json=runFinished,proto3,oneof"`
}

type Event_RunError struct {
	RunError *RunErrorPayload `protobuf:"bytes,20,opt,name=run_error,json=runError,proto3,oneof"`
}

type Event_UnknownPayload struct {
	// For unknown event types
	UnknownPayload *structpb.Struct `protobuf:"bytes,100,opt,name=unknown_payload,json=unknownPayload,proto3,oneof"`
}

func (*Event_StepStarted) isEvent_Payload() {}

func (*Event_StepFinished) isEvent_Payload() {}

func (*Event_NodeStatusChanged) isEvent_Payload() {}

func (*Event_LlmCallStarted) isEvent_Payload() {}

func (*Event_LlmCallCompleted) isEvent_Payload() {}

func (*Event_ToolInvoked) isEvent_Payload() {}

func (*Event_ToolReturned) isEvent_Payload() {}

func (*Event_NodeCreated) isEvent_Payload() {}

func (*Event_PlanReceived) isEvent_Payload() {}

func (*Event_NodeAdded) isEvent_Payload() {}

func (*Event_EdgeAdded) isEvent_Payload() {}

func (*Event_InnerGraphBuilt) isEvent_Payload() {}

func (*Event_NodeResultAvailable) isEvent_Payload() {}

func (*Event_RunStarted) isEvent_Payload() {}

func (*Event_RunFinished) isEvent_Payload() {}

func (*Event_RunError) isEvent_Payload() {}

func (*Event_UnknownPayload) isEvent_Payload() {}

// EventsResponse - Response from the events API
type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ConnectionStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=events.ConnectionStatus" json:"status,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_proto_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{19}
}

func (x *EventsResponse) GetStatus() ConnectionStatus {
	if x != nil {
		return x.Status
	}
	return ConnectionStatus_CONNECTION_STATUS_UNSPECIFIED
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type RunFinishedPayload_TokenUsageSummary struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalPromptTokens     int32                  `protobuf:"varint,1,opt,name=total_prompt_tokens,json=totalPromptTokens,proto3" json:"total_prompt_tokens,omitempty"`
	TotalCompletionTokens int32                  `protobuf:"varint,2,opt,name=total_completion_tokens,json=totalCompletionTokens,proto3" json:"total_completion_tokens,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RunFinishedPayload_TokenUsageSummary) Reset() {
	*x = RunFinishedPayload_TokenUsageSummary{}
	mi := &file_proto_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinishedPayload_TokenUsageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinishedPayload_TokenUsageSummary) ProtoMessage() {}

func (x *RunFinishedPayload_TokenUsageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinishedPayload_TokenUsageSummary.ProtoReflect.Descriptor instead.
func (*RunFinishedPayload_TokenUsageSummary) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{16, 0}
}

func (x *RunFinishedPayload_TokenUsageSummary) GetTotalPromptTokens() int32 {
	if x != nil {
		return x.TotalPromptTokens
	}
	return 0
}

func (x *RunFinishedPayload_TokenUsageSummary) GetTotalCompletionTokens() int32 {
	if x != nil {
		return x.TotalCompletionTokens
	}
	return 0
}

type RunFinishedPayload_NodeStatistics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalCreated   int32                  `protobuf:"varint,1,opt,name=total_created,json=totalCreated,proto3" json:"total_created,omitempty"`
	TotalCompleted int32                  `protobuf:"varint,2,opt,name=total_completed,json=totalCompleted,proto3" json:"total_completed,omitempty"`
	ByType         map[string]int32       `protobuf:"bytes,3,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunFinishedPayload_NodeStatistics) Reset() {
	*x = RunFinishedPayload_NodeStatistics{}
	mi := &file_proto_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinishedPayload_NodeStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinishedPayload_NodeStatistics) ProtoMessage() {}

func (x *RunFinishedPayload_NodeStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinishedPayload_NodeStatistics.ProtoReflect.Descriptor instead.
func (*RunFinishedPayload_NodeStatistics) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{16, 1}
}

func (x *RunFinishedPayload_NodeStatistics) GetTotalCreated() int32 {
	if x != nil {
		return x.TotalCreated
	}
	return 0
}

func (x *RunFinishedPayload_NodeStatistics) GetTotalCompleted() int32 {
	if x != nil {
		return x.TotalCompleted
	}
	return 0
}

func (x *RunFinishedPayload_NodeStatistics) GetByType() map[string]int32 {
	if x != nil {
		return x.ByType
	}
	return nil
}

type RunFinishedPayload_SearchStatistics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalSearches       int32                  `protobuf:"varint,1,opt,name=total_searches,json=totalSearches,proto3" json:"total_searches,omitempty"`
	TotalPagesProcessed int32                  `protobuf:"varint,2,opt,name=total_pages_processed,json=totalPagesProcessed,proto3" json:"total_pages_processed,omitempty"`
	TotalSearchTokens   int32                  `protobuf:"varint,3,opt,name=total_search_tokens,json=totalSearchTokens,proto3" json:"total_search_tokens,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunFinishedPayload_SearchStatistics) Reset() {
	*x = RunFinishedPayload_SearchStatistics{}
	mi := &file_proto_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFinishedPayload_SearchStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFinishedPayload_SearchStatistics) ProtoMessage() {}

func (x *RunFinishedPayload_SearchStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFinishedPayload_SearchStatistics.ProtoReflect.Descriptor instead.
func (*RunFinishedPayload_SearchStatistics) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{16, 2}
}

func (x *RunFinishedPayload_SearchStatistics) GetTotalSearches() int32 {
	if x != nil {
		return x.TotalSearches
	}
	return 0
}

func (x *RunFinishedPayload_SearchStatistics) GetTotalPagesProcessed() int32 {
	if x != nil {
		return x.TotalPagesProcessed
	}
	return 0
}

func (x *RunFinishedPayload_SearchStatistics) GetTotalSearchTokens() int32 {
	if x != nil {
		return x.TotalSearchTokens
	}
	return 0
}

type RunErrorPayload_Context struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LastSuccessfulStep  int32                  `protobuf:"varint,1,opt,name=last_successful_step,json=lastSuccessfulStep,proto3" json:"last_successful_step,omitempty"`
	TotalProcessedItems int32                  `protobuf:"varint,2,opt,name=total_processed_items,json=totalProcessedItems,proto3" json:"total_processed_items,omitempty"`
	LastItemId          string                 `protobuf:"bytes,3,opt,name=last_item_id,json=lastItemId,proto3" json:"last_item_id,omitempty"`
	EngineBackend       *string                `protobuf:"bytes,4,opt,name=engine_backend,json=engineBackend,proto3,oneof" json:"engine_backend,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunErrorPayload_Context) Reset() {
	*x = RunErrorPayload_Context{}
	mi := &file_proto_events_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunErrorPayload_Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunErrorPayload_Context) ProtoMessage() {}

func (x *RunErrorPayload_Context) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunErrorPayload_Context.ProtoReflect.Descriptor instead.
func (*RunErrorPayload_Context) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{17, 0}
}

func (x *RunErrorPayload_Context) GetLastSuccessfulStep() int32 {
	if x != nil {
		return x.LastSuccessfulStep
	}
	return 0
}

func (x *RunErrorPayload_Context) GetTotalProcessedItems() int32 {
	if x != nil {
		return x.TotalProcessedItems
	}
	return 0
}

func (x *RunErrorPayload_Context) GetLastItemId() string {
	if x != nil {
		return x.LastItemId
	}
	return ""
}

func (x *RunErrorPayload_Context) GetEngineBackend() string {
	if x != nil && x.EngineBackend != nil {
		return *x.EngineBackend
	}
	return ""
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\x06events\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\n" +
	"LlmMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"w\n" +
	"\x12StepStartedPayload\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_goal\x18\x03 \x01(\tR\bnodeGoal\x12\x17\n" +
	"\aroot_id\x18\x04 \x01(\tR\x06rootId\"\xb1\x01\n" +
	"\x13StepFinishedPayload\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vaction_name\x18\x03 \x01(\tR\n" +
	"actionName\x12!\n" +
	"\fstatus_after\x18\x04 \x01(\tR\vstatusAfter\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x01R\x0fdurationSeconds\"\xaf\x01\n" +
	"\x17NodeStatusChangePayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_goal\x18\x02 \x01(\tR\bnodeGoal\x12\x1d\n" +
	"\n" +
	"old_status\x18\x03 \x01(\tR\toldStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x04 \x01(\tR\tnewStatus\x12\x17\n" +
	"\x04step\x18\x05 \x01(\x05H\x00R\x04step\x88\x01\x01B\a\n" +
	"\x05_step\"\xad\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x1c\n" +
	"\anode_id\x18\x04 \x01(\tH\x01R\x06nodeId\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_node_id\"\xbc\x02\n" +
	"\x15LlmCallStartedPayload\x12\x1f\n" +
	"\vagent_class\x18\x01 \x01(\tR\n" +
	"agentClass\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12*\n" +
	"\x06prompt\x18\x03 \x03(\v2\x12.events.LlmMessageR\x06prompt\x12%\n" +
	"\x0eprompt_preview\x18\x04 \x01(\tR\rpromptPreview\x12\x17\n" +
	"\x04step\x18\x05 \x01(\x05H\x00R\x04step\x88\x01\x01\x12\x1c\n" +
	"\anode_id\x18\x06 \x01(\tH\x01R\x06nodeId\x88\x01\x01\x12$\n" +
	"\vaction_name\x18\a \x01(\tH\x02R\n" +
	"actionName\x88\x01\x01\x12\x17\n" +
	"\acall_id\x18\b \x01(\tR\x06callIdB\a\n" +
	"\x05_stepB\n" +
	"\n" +
	"\b_node_idB\x0e\n" +
	"\f_action_name\"\xc8\x03\n" +
	"\x17LlmCallCompletedPayload\x12\x1f\n" +
	"\vagent_class\x18\x01 \x01(\tR\n" +
	"agentClass\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x01R\x0fdurationSeconds\x12\x1a\n" +
	"\bresponse\x18\x04 \x01(\tR\bresponse\x12%\n" +
	"\x0eresult_summary\x18\x05 \x01(\tR\rresultSummary\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x17\n" +
	"\x04step\x18\a \x01(\x05H\x01R\x04step\x88\x01\x01\x12\x1c\n" +
	"\anode_id\x18\b \x01(\tH\x02R\x06nodeId\x88\x01\x01\x128\n" +
	"\vtoken_usage\x18\t \x01(\v2\x12.events.TokenUsageH\x03R\n" +
	"tokenUsage\x88\x01\x01\x12$\n" +
	"\vaction_name\x18\n" +
	" \x01(\tH\x04R\n" +
	"actionName\x88\x01\x01\x12\x17\n" +
	"\acall_id\x18\v \x01(\tR\x06callIdB\b\n" +
	"\x06_errorB\a\n" +
	"\x05_stepB\n" +
	"\n" +
	"\b_node_idB\x0e\n" +
	"\f_token_usageB\x0e\n" +
	"\f_action_name\"\x93\x02\n" +
	"\x12ToolInvokedPayload\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x19\n" +
	"\bapi_name\x18\x02 \x01(\tR\aapiName\x12!\n" +
	"\fargs_summary\x18\x03 \x01(\tR\vargsSummary\x12\x1c\n" +
	"\anode_id\x18\x04 \x01(\tH\x00R\x06nodeId\x88\x01\x01\x12\x17\n" +
	"\x04step\x18\x05 \x01(\x05H\x01R\x04step\x88\x01\x01\x12$\n" +
	"\vagent_class\x18\x06 \x01(\tH\x02R\n" +
	"agentClass\x88\x01\x01\x12 \n" +
	"\ftool_call_id\x18\a \x01(\tR\n" +
	"toolCallIdB\n" +
	"\n" +
	"\b_node_idB\a\n" +
	"\x05_stepB\x0e\n" +
	"\f_agent_class\"\xfe\x02\n" +
	"\x13ToolReturnedPayload\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x19\n" +
	"\bapi_name\x18\x02 \x01(\tR\aapiName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x01R\x0fdurationSeconds\x12%\n" +
	"\x0eresult_summary\x18\x05 \x01(\tR\rresultSummary\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01\x12\x1c\n" +
	"\anode_id\x18\a \x01(\tH\x01R\x06nodeId\x88\x01\x01\x12\x17\n" +
	"\x04step\x18\b \x01(\x05H\x02R\x04step\x88\x01\x01\x12$\n" +
	"\vagent_class\x18\t \x01(\tH\x03R\n" +
	"agentClass\x88\x01\x01\x12 \n" +
	"\ftool_call_id\x18\n" +
	" \x01(\tR\n" +
	"toolCallIdB\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_node_idB\a\n" +
	"\x05_stepB\x0e\n" +
	"\f_agent_class\"\xe4\x02\n" +
	"\x12NodeCreatedPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bnode_nid\x18\x02 \x01(\tR\anodeNid\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\x12\x1b\n" +
	"\ttask_goal\x18\x05 \x01(\tR\btaskGoal\x12\x14\n" +
	"\x05layer\x18\x06 \x01(\x05R\x05layer\x12'\n" +
	"\router_node_id\x18\a \x01(\tH\x00R\vouterNodeId\x88\x01\x01\x12 \n" +
	"\froot_node_id\x18\b \x01(\tR\n" +
	"rootNodeId\x12.\n" +
	"\x13initial_parent_nids\x18\t \x03(\tR\x11initialParentNids\x12\x17\n" +
	"\x04step\x18\n" +
	" \x01(\x05H\x01R\x04step\x88\x01\x01B\x10\n" +
	"\x0e_outer_node_idB\a\n" +
	"\x05_step\"\xe4\x01\n" +
	"\x13PlanReceivedPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\braw_plan\x18\x02 \x01(\v2\x17.google.protobuf.StructR\arawPlan\x12\x17\n" +
	"\x04step\x18\x03 \x01(\x05H\x00R\x04step\x88\x01\x01\x12 \n" +
	"\ttask_type\x18\x04 \x01(\tH\x01R\btaskType\x88\x01\x01\x12 \n" +
	"\ttask_goal\x18\x05 \x01(\tH\x02R\btaskGoal\x88\x01\x01B\a\n" +
	"\x05_stepB\f\n" +
	"\n" +
	"_task_typeB\f\n" +
	"\n" +
	"_task_goal\"\x8d\x02\n" +
	"\x10NodeAddedPayload\x12-\n" +
	"\x13graph_owner_node_id\x18\x01 \x01(\tR\x10graphOwnerNodeId\x12\"\n" +
	"\radded_node_id\x18\x02 \x01(\tR\vaddedNodeId\x12$\n" +
	"\x0eadded_node_nid\x18\x03 \x01(\tR\faddedNodeNid\x12\x17\n" +
	"\x04step\x18\x04 \x01(\x05H\x00R\x04step\x88\x01\x01\x12 \n" +
	"\ttask_type\x18\x05 \x01(\tH\x01R\btaskType\x88\x01\x01\x12 \n" +
	"\ttask_goal\x18\x06 \x01(\tH\x02R\btaskGoal\x88\x01\x01B\a\n" +
	"\x05_stepB\f\n" +
	"\n" +
	"_task_typeB\f\n" +
	"\n" +
	"_task_goal\"\xdb\x02\n" +
	"\x10EdgeAddedPayload\x12-\n" +
	"\x13graph_owner_node_id\x18\x01 \x01(\tR\x10graphOwnerNodeId\x12$\n" +
	"\x0eparent_node_id\x18\x02 \x01(\tR\fparentNodeId\x12\"\n" +
	"\rchild_node_id\x18\x03 \x01(\tR\vchildNodeId\x12&\n" +
	"\x0fparent_node_nid\x18\x04 \x01(\tR\rparentNodeNid\x12$\n" +
	"\x0echild_node_nid\x18\x05 \x01(\tR\fchildNodeNid\x12\x17\n" +
	"\x04step\x18\x06 \x01(\x05H\x00R\x04step\x88\x01\x01\x12 \n" +
	"\ttask_type\x18\a \x01(\tH\x01R\btaskType\x88\x01\x01\x12 \n" +
	"\ttask_goal\x18\b \x01(\tH\x02R\btaskGoal\x88\x01\x01B\a\n" +
	"\x05_stepB\f\n" +
	"\n" +
	"_task_typeB\f\n" +
	"\n" +
	"_task_goal\"\x8c\x02\n" +
	"\x16InnerGraphBuiltPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_count\x18\x02 \x01(\x05R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x03 \x01(\x05R\tedgeCount\x12\x19\n" +
	"\bnode_ids\x18\x04 \x03(\tR\anodeIds\x12\x17\n" +
	"\x04step\x18\x05 \x01(\x05H\x00R\x04step\x88\x01\x01\x12 \n" +
	"\ttask_type\x18\x06 \x01(\tH\x01R\btaskType\x88\x01\x01\x12 \n" +
	"\ttask_goal\x18\a \x01(\tH\x02R\btaskGoal\x88\x01\x01B\a\n" +
	"\x05_stepB\f\n" +
	"\n" +
	"_task_typeB\f\n" +
	"\n" +
	"_task_goal\"\xff\x01\n" +
	"\x1aNodeResultAvailablePayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x12%\n" +
	"\x0eresult_summary\x18\x03 \x01(\tR\rresultSummary\x12\x17\n" +
	"\x04step\x18\x04 \x01(\x05H\x00R\x04step\x88\x01\x01\x12 \n" +
	"\ttask_type\x18\x05 \x01(\tH\x01R\btaskType\x88\x01\x01\x12 \n" +
	"\ttask_goal\x18\x06 \x01(\tH\x02R\btaskGoal\x88\x01\x01B\a\n" +
	"\x05_stepB\f\n" +
	"\n" +
	"_task_typeB\f\n" +
	"\n" +
	"_task_goal\"\xd8\x01\n" +
	"\x11RunStartedPayload\x126\n" +
	"\n" +
	"input_data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\tinputData\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x19\n" +
	"\brun_mode\x18\x03 \x01(\tR\arunMode\x12?\n" +
	"\rtimestamp_utc\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ftimestampUtc\"\x83\b\n" +
	"\x12RunFinishedPayload\x12\x1f\n" +
	"\vtotal_steps\x18\x01 \x01(\x05R\n" +
	"totalSteps\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x01R\x0fdurationSeconds\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\x05R\n" +
	"totalNodes\x12&\n" +
	"\x0ftotal_llm_calls\x18\x04 \x01(\x05R\rtotalLlmCalls\x12(\n" +
	"\x10total_tool_calls\x18\x05 \x01(\x05R\x0etotalToolCalls\x12\\\n" +
	"\x13token_usage_summary\x18\x06 \x01(\v2,.events.RunFinishedPayload.TokenUsageSummaryR\x11tokenUsageSummary\x12R\n" +
	"\x0fnode_statistics\x18\a \x01(\v2).events.RunFinishedPayload.NodeStatisticsR\x0enodeStatistics\x12]\n" +
	"\x11search_statistics\x18\b \x01(\v2+.events.RunFinishedPayload.SearchStatisticsH\x00R\x10searchStatistics\x88\x01\x01\x1a{\n" +
	"\x11TokenUsageSummary\x12.\n" +
	"\x13total_prompt_tokens\x18\x01 \x01(\x05R\x11totalPromptTokens\x126\n" +
	"\x17total_completion_tokens\x18\x02 \x01(\x05R\x15totalCompletionTokens\x1a\xe9\x01\n" +
	"\x0eNodeStatistics\x12#\n" +
	"\rtotal_created\x18\x01 \x01(\x05R\ftotalCreated\x12'\n" +
	"\x0ftotal_completed\x18\x02 \x01(\x05R\x0etotalCompleted\x12N\n" +
	"\aby_type\x18\x03 \x03(\v25.events.RunFinishedPayload.NodeStatistics.ByTypeEntryR\x06byType\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a\x9d\x01\n" +
	"\x10SearchStatistics\x12%\n" +
	"\x0etotal_searches\x18\x01 \x01(\x05R\rtotalSearches\x122\n" +
	"\x15total_pages_processed\x18\x02 \x01(\x05R\x13totalPagesProcessed\x12.\n" +
	"\x13total_search_tokens\x18\x03 \x01(\x05R\x11totalSearchTokensB\x14\n" +
	"\x12_search_statistics\"\xd0\x03\n" +
	"\x0fRunErrorPayload\x12\x1d\n" +
	"\n" +
	"error_type\x18\x01 \x01(\tR\terrorType\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x12\x1c\n" +
	"\anode_id\x18\x04 \x01(\tH\x00R\x06nodeId\x88\x01\x01\x12\x17\n" +
	"\x04step\x18\x05 \x01(\x05H\x01R\x04step\x88\x01\x01\x129\n" +
	"\acontext\x18\x06 \x01(\v2\x1f.events.RunErrorPayload.ContextR\acontext\x1a\xd0\x01\n" +
	"\aContext\x120\n" +
	"\x14last_successful_step\x18\x01 \x01(\x05R\x12lastSuccessfulStep\x122\n" +
	"\x15total_processed_items\x18\x02 \x01(\x05R\x13totalProcessedItems\x12 \n" +
	"\flast_item_id\x18\x03 \x01(\tR\n" +
	"lastItemId\x12*\n" +
	"\x0eengine_backend\x18\x04 \x01(\tH\x00R\rengineBackend\x88\x01\x01B\x11\n" +
	"\x0f_engine_backendB\n" +
	"\n" +
	"\b_node_idB\a\n" +
	"\x05_step\"\xd7\n" +
	"\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x11.events.EventTypeR\teventType\x12\x1a\n" +
	"\x06run_id\x18\x04 \x01(\tH\x01R\x05runId\x88\x01\x01\x12?\n" +
	"\fstep_started\x18\x05 \x01(\v2\x1a.events.StepStartedPayloadH\x00R\vstepStarted\x12B\n" +
	"\rstep_finished\x18\x06 \x01(\v2\x1b.events.StepFinishedPayloadH\x00R\fstepFinished\x12Q\n" +
	"\x13node_status_changed\x18\a \x01(\v2\x1f.events.NodeStatusChangePayloadH\x00R\x11nodeStatusChanged\x12I\n" +
	"\x10llm_call_started\x18\b \x01(\v2\x1d.events.LlmCallStartedPayloadH\x00R\x0ellmCallStarted\x12O\n" +
	"\x12llm_call_completed\x18\t \x01(\v2\x1f.events.LlmCallCompletedPayloadH\x00R\x10llmCallCompleted\x12?\n" +
	"\ftool_invoked\x18\n" +
	" \x01(\v2\x1a.events.ToolInvokedPayloadH\x00R\vtoolInvoked\x12B\n" +
	"\rtool_returned\x18\v \x01(\v2\x1b.events.ToolReturnedPayloadH\x00R\ftoolReturned\x12?\n" +
	"\fnode_created\x18\f \x01(\v2\x1a.events.NodeCreatedPayloadH\x00R\vnodeCreated\x12B\n" +
	"\rplan_received\x18\r \x01(\v2\x1b.events.PlanReceivedPayloadH\x00R\fplanReceived\x129\n" +
	"\n" +
	"node_added\x18\x0e \x01(\v2\x18.events.NodeAddedPayloadH\x00R\tnodeAdded\x129\n" +
	"\n" +
	"edge_added\x18\x0f \x01(\v2\x18.events.EdgeAddedPayloadH\x00R\tedgeAdded\x12L\n" +
	"\x11inner_graph_built\x18\x10 \x01(\v2\x1e.events.InnerGraphBuiltPayloadH\x00R\x0finnerGraphBuilt\x12X\n" +
	"\x15node_result_available\x18\x11 \x01(\v2\".events.NodeResultAvailablePayloadH\x00R\x13nodeResultAvailable\x12<\n" +
	"\vrun_started\x18\x12 \x01(\v2\x19.events.RunStartedPayloadH\x00R\n" +
	"runStarted\x12?\n" +
	"\frun_finished\x18\x13 \x01(\v2\x1a.events.RunFinishedPayloadH\x00R\vrunFinished\x126\n" +
	"\trun_error\x18\x14 \x01(\v2\x17.events.RunErrorPayloadH\x00R\brunError\x12B\n" +
	"\x0funknown_payload\x18d \x01(\v2\x17.google.protobuf.StructH\x00R\x0eunknownPayloadB\t\n" +
	"\apayloadB\t\n" +
	"\a_run_id\"i\n" +
	"\x0eEventsResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.events.ConnectionStatusR\x06status\x12%\n" +
	"\x06events\x18\x02 \x03(\v2\r.events.EventR\x06events*\x91\x04\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_STEP_STARTED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_STEP_FINISHED\x10\x02\x12\"\n" +
	"\x1eEVENT_TYPE_NODE_STATUS_CHANGED\x10\x03\x12\x1f\n" +
	"\x1bEVENT_TYPE_LLM_CALL_STARTED\x10\x04\x12!\n" +
	"\x1dEVENT_TYPE_LLM_CALL_COMPLETED\x10\x05\x12\x1b\n" +
	"\x17EVENT_TYPE_TOOL_INVOKED\x10\x06\x12\x1c\n" +
	"\x18EVENT_TYPE_TOOL_RETURNED\x10\a\x12\x1b\n" +
	"\x17EVENT_TYPE_NODE_CREATED\x10\b\x12\x1c\n" +
	"\x18EVENT_TYPE_PLAN_RECEIVED\x10\t\x12\x19\n" +
	"\x15EVENT_TYPE_NODE_ADDED\x10\n" +
	"\x12\x19\n" +
	"\x15EVENT_TYPE_EDGE_ADDED\x10\v\x12 \n" +
	"\x1cEVENT_TYPE_INNER_GRAPH_BUILT\x10\f\x12$\n" +
	" EVENT_TYPE_NODE_RESULT_AVAILABLE\x10\r\x12\x1a\n" +
	"\x16EVENT_TYPE_RUN_STARTED\x10\x0e\x12\x1b\n" +
	"\x17EVENT_TYPE_RUN_FINISHED\x10\x0f\x12\x18\n" +
	"\x14EVENT_TYPE_RUN_ERROR\x10\x10*\x9c\x01\n" +
	"\x10ConnectionStatus\x12!\n" +
	"\x1dCONNECTION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONNECTION_STATUS_CONNECTING\x10\x01\x12\x1f\n" +
	"\x1bCONNECTION_STATUS_CONNECTED\x10\x02\x12\"\n" +
	"\x1eCONNECTION_STATUS_DISCONNECTED\x10\x03B0Z.github.com/go-go-golems/go-go-agent/pkg/eventsb\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_events_proto_goTypes = []any{
	(EventType)(0),                               // 0: events.EventType
	(ConnectionStatus)(0),                        // 1: events.ConnectionStatus
	(*LlmMessage)(nil),                           // 2: events.LlmMessage
	(*StepStartedPayload)(nil),                   // 3: events.StepStartedPayload
	(*StepFinishedPayload)(nil),                  // 4: events.StepFinishedPayload
	(*NodeStatusChangePayload)(nil),              // 5: events.NodeStatusChangePayload
	(*TokenUsage)(nil),                           // 6: events.TokenUsage
	(*LlmCallStartedPayload)(nil),                // 7: events.LlmCallStartedPayload
	(*LlmCallCompletedPayload)(nil),              // 8: events.LlmCallCompletedPayload
	(*ToolInvokedPayload)(nil),                   // 9: events.ToolInvokedPayload
	(*ToolReturnedPayload)(nil),                  // 10: events.ToolReturnedPayload
	(*NodeCreatedPayload)(nil),                   // 11: events.NodeCreatedPayload
	(*PlanReceivedPayload)(nil),                  // 12: events.PlanReceivedPayload
	(*NodeAddedPayload)(nil),                     // 13: events.NodeAddedPayload
	(*EdgeAddedPayload)(nil),                     // 14: events.EdgeAddedPayload
	(*InnerGraphBuiltPayload)(nil),               // 15: events.InnerGraphBuiltPayload
	(*NodeResultAvailablePayload)(nil),           // 16: events.NodeResultAvailablePayload
	(*RunStartedPayload)(nil),                    // 17: events.RunStartedPayload
	(*RunFinishedPayload)(nil),                   // 18: events.RunFinishedPayload
	(*RunErrorPayload)(nil),                      // 19: events.RunErrorPayload
	(*Event)(nil),                                // 20: events.Event
	(*EventsResponse)(nil),                       // 21: events.EventsResponse
	(*RunFinishedPayload_TokenUsageSummary)(nil), // 22: events.RunFinishedPayload.TokenUsageSummary
	(*RunFinishedPayload_NodeStatistics)(nil),    // 23: events.RunFinishedPayload.NodeStatistics
	(*RunFinishedPayload_SearchStatistics)(nil),  // 24: events.RunFinishedPayload.SearchStatistics
	nil,                             // 25: events.RunFinishedPayload.NodeStatistics.ByTypeEntry
	(*RunErrorPayload_Context)(nil), // 26: events.RunErrorPayload.Context
	(*structpb.Struct)(nil),         // 27: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),   // 28: google.protobuf.Timestamp
}
var file_proto_events_proto_depIdxs = []int32{
	2,  // 0: events.LlmCallStartedPayload.prompt:type_name -> events.LlmMessage
	6,  // 1: events.LlmCallCompletedPayload.token_usage:type_name -> events.TokenUsage
	27, // 2: events.PlanReceivedPayload.raw_plan:type_name -> google.protobuf.Struct
	27, // 3: events.RunStartedPayload.input_data:type_name -> google.protobuf.Struct
	27, // 4: events.RunStartedPayload.config:type_name -> google.protobuf.Struct
	28, // 5: events.RunStartedPayload.timestamp_utc:type_name -> google.protobuf.Timestamp
	22, // 6: events.RunFinishedPayload.token_usage_summary:type_name -> events.RunFinishedPayload.TokenUsageSummary
	23, // 7: events.RunFinishedPayload.node_statistics:type_name -> events.RunFinishedPayload.NodeStatistics
	24, // 8: events.RunFinishedPayload.search_statistics:type_name -> events.RunFinishedPayload.SearchStatistics
	26, // 9: events.RunErrorPayload.context:type_name -> events.RunErrorPayload.Context
	28, // 10: events.Event.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: events.Event.event_type:type_name -> events.EventType
	3,  // 12: events.Event.step_started:type_name -> events.StepStartedPayload
	4,  // 13: events.Event.step_finished:type_name -> events.StepFinishedPayload
	5,  // 14: events.Event.node_status_changed:type_name -> events.NodeStatusChangePayload
	7,  // 15: events.Event.llm_call_started:type_name -> events.LlmCallStartedPayload
	8,  // 16: events.Event.llm_call_completed:type_name -> events.LlmCallCompletedPayload
	9,  // 17: events.Event.tool_invoked:type_name -> events.ToolInvokedPayload
	10, // 18: events.Event.tool_returned:type_name -> events.ToolReturnedPayload
	11, // 19: events.Event.node_created:type_name -> events.NodeCreatedPayload
	12, // 20: events.Event.plan_received:type_name -> events.PlanReceivedPayload
	13, // 21: events.Event.node_added:type_name -> events.NodeAddedPayload
	14, // 22: events.Event.edge_added:type_name -> events.EdgeAddedPayload
	15, // 23: events.Event.inner_graph_built:type_name -> events.InnerGraphBuiltPayload
	16, // 24: events.Event.node_result_available:type_name -> events.NodeResultAvailablePayload
	17, // 25: events.Event.run_started:type_name -> events.RunStartedPayload
	18, // 26: events.Event.run_finished:type_name -> events.RunFinishedPayload
	19, // 27: events.Event.run_error:type_name -> events.RunErrorPayload
	27, // 28: events.Event.unknown_payload:type_name -> google.protobuf.Struct
	1,  // 29: events.EventsResponse.status:type_name -> events.ConnectionStatus
	20, // 30: events.EventsResponse.events:type_name -> events.Event
	25, // 31: events.RunFinishedPayload.NodeStatistics.by_type:type_name -> events.RunFinishedPayload.NodeStatistics.ByTypeEntry
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	file_proto_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[13].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_events_proto_msgTypes[18].OneofWrappers = []any{
		(*Event_StepStarted)(nil),
		(*Event_StepFinished)(nil),
		(*Event_NodeStatusChanged)(nil),
		(*Event_LlmCallStarted)(nil),
		(*Event_LlmCallCompleted)(nil),
		(*Event_ToolInvoked)(nil),
		(*Event_ToolReturned)(nil),
		(*Event_NodeCreated)(nil),
		(*Event_PlanReceived)(nil),
		(*Event_NodeAdded)(nil),
		(*Event_EdgeAdded)(nil),
		(*Event_InnerGraphBuilt)(nil),
		(*Event_NodeResultAvailable)(nil),
		(*Event_RunStarted)(nil),
		(*Event_RunFinished)(nil),
		(*Event_RunError)(nil),
		(*Event_UnknownPayload)(nil),
	}
	file_proto_events_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		EnumInfos:         file_proto_events_proto_enumTypes,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
